### ISSUE TITLE
Feature Request: Allow `/[...catchAll]` routes to handle `/` (index) routes

### ISSUE THREAD

**Issue by hamlim** [wakujs/waku#1518]
Split off from #1508 and #1507 

## Details:

If an app defines a catch-all route - that catch-all route will never be used for "index" paths. 

Example:

```sh
src/
  pages/
    [...catchAll].tsx
```

Given the application source code above, a request to `/` should ideally render the `[...catchAll]` page but it doesn't currently.

I think this happens for "nested" index routes too, e.g.

```sh
src/
  pages/
    foo/
      [...catchAll].tsx
```

`foo/[...catchAll]` should be used to handle a request to `/foo`

**Comment by dai-shi** [comment]
fixed by #1508

**Comment by hamlim** [comment]
This bug still exists, #1508 only addressed the api route issue and not this issue.

Simple reproduction here: https://github.com/hamlim/repro-catch-all-not-handling-index-routes

**Comment by dai-shi** [comment]
That was my bad.

> If an app defines a catch-all route - that catch-all route will never be used for "index" paths.

I think it's how it's designed. @tylersayshi can confirm if we should fix it.
Is it fixable within create-pages.ts, or does it require some changes in define-router.ts?

**Comment by hamlim** [comment]
I haven't looked too closely at what might need to change to support this just yet, might be able to do that this week.

I'm also fine with calling this a feature request as opposed to a bug, I had thought that Next.js supports this feature but it turns out that they use a slightly different syntax for what they call "optional catch-all" routes that will be used for the "index" route on a path too - https://nextjs.org/docs/app/api-reference/file-conventions/dynamic-routes#optional-catch-all-segments

**Comment by dai-shi** [comment]
Yeah, I'd consider it a feature request and it's reasonable.
